const participants = {
  "ceiling": {
    "a": "10",
    "b": "10",
    "c": "20",
    "d": "20",
    "e": "30",
    "f": "30",
    "g": "40",
    "h": "40"
  },
  "participants": [
    {
      "name": "Andrey Kudryavtsev",
      "title": "Systems Architect",
      "country": "RU",
      "a": "5",
      "b": "5",
      "c": "9",
      "d": "19",
      "e": "17",
      "f": "25",
      "g": "30",
      "h": "39"
    },
    {
      "name": "Lawrence Xu",
      "title": "Senior Systems Engineer",
      "country": "CN",
      "a": "5",
      "b": "6",
      "c": "10",
      "d": "20",
      "e": "25",
      "f": "17",
      "g": "32",
      "h": "31"
    },
    {
      "name": "Nikolay Titov",
      "title": "Lead Frontend Developer",
      "country": "UA",
      "a": "4",
      "b": "5",
      "c": "4",
      "d": "11",
      "e": "29",
      "f": "12",
      "g": "39",
      "h": "36"
    },
    {
      "name": "Alexey Khokhlov",
      "title": "Cloud Platform Architect",
      "country": "RU",
      "a": "10",
      "b": "7",
      "c": "7",
      "d": "19",
      "e": "6",
      "f": "17",
      "g": "33",
      "h": "39"
    },
    {
      "name": "Shuichi Watanabe",
      "title": "IT Architect",
      "country": "JP",
      "a": "0",
      "b": "7",
      "c": "7",
      "d": "19",
      "e": "11",
      "f": "29",
      "g": "30",
      "h": "30"
    },
    {
      "name": "Sergey Murashko",
      "title": "Lead Developer",
      "country": "BY",
      "a": "9",
      "b": "0",
      "c": "7",
      "d": "8",
      "e": "29",
      "f": "25",
      "g": "34",
      "h": "17"
    },
    {
      "name": "Sergey Mironov",
      "title": "Senior Frontend Engineer",
      "country": "RU",
      "a": "0",
      "b": "0",
      "c": "10",
      "d": "19",
      "e": "13",
      "f": "9",
      "g": "38",
      "h": "40"
    },
    {
      "name": "Rohit Kumar",
      "title": "OpenStack Operations Engineer",
      "country": "IN",
      "a": "8",
      "b": "3",
      "c": "17",
      "d": "4",
      "e": "15",
      "f": "18",
      "g": "33",
      "h": "29"
    },
    {
      "name": "Ajay Bhandari",
      "title": "Java Chief Architect",
      "country": "IN",
      "a": "0",
      "b": "4",
      "c": "12",
      "d": "16",
      "e": "3",
      "f": "20",
      "g": "31",
      "h": "36"
    },
    {
      "name": "Alexey Durov",
      "title": "Software Architect",
      "country": "BY",
      "a": "0",
      "b": "2",
      "c": "9",
      "d": "11",
      "e": "11",
      "f": "16",
      "g": "29",
      "h": "37"
    },
    {
      "name": "Anand Patel",
      "title": "Cloud Solutions Architect",
      "country": "US",
      "a": "8",
      "b": "2",
      "c": "7",
      "d": "2",
      "e": "12",
      "f": "21",
      "g": "40",
      "h": "20"
    },
    {
      "name": "Mikhail Demidov",
      "title": "Java Chief Architect",
      "country": "RU",
      "a": "7",
      "b": "6",
      "c": "8",
      "d": "11",
      "e": "14",
      "f": "18",
      "g": "17",
      "h": "29"
    },
    {
      "name": "Serg Bataev",
      "title": "OpenStack Operations Engineer",
      "country": "UA",
      "a": "6",
      "b": "4",
      "c": "14",
      "d": "12",
      "e": "23",
      "f": "23",
      "g": "19",
      "h": "7"
    },
    {
      "name": "Takaaki Suzuki",
      "title": "Architect",
      "country": "JP",
      "a": "7",
      "b": "0",
      "c": "6",
      "d": "15",
      "e": "29",
      "f": "21",
      "g": "20",
      "h": "10"
    },
    {
      "name": "Rich Heilman",
      "title": "Senior Architect",
      "country": "US",
      "a": "3",
      "b": "1",
      "c": "0",
      "d": "7",
      "e": "20",
      "f": "16",
      "g": "20",
      "h": "40"
    },
    {
      "name": "Zhibo Liu",
      "title": "Cloud Solutions Architect",
      "country": "CN",
      "a": "2",
      "b": "10",
      "c": "9",
      "d": "11",
      "e": "5",
      "f": "18",
      "g": "30",
      "h": "22"
    },
    {
      "name": "Sarath Chandra",
      "title": "IT Architect",
      "country": "IN",
      "a": "3",
      "b": "10",
      "c": "16",
      "d": "8",
      "e": "28",
      "f": "11",
      "g": "24",
      "h": "5"
    },
    {
      "name": "Andriy Rybak",
      "title": "Senior Frontend Engineer",
      "country": "UA",
      "a": "3",
      "b": "7",
      "c": "19",
      "d": "13",
      "e": "19",
      "f": "15",
      "g": "26",
      "h": "2"
    },
    {
      "name": "Viktar Savoska",
      "title": "Software Architect",
      "country": "BY",
      "a": "8",
      "b": "9",
      "c": "14",
      "d": "10",
      "e": "9",
      "f": "18",
      "g": "31",
      "h": "4"
    },
    {
      "name": "Roman Boiko",
      "title": "DevOps Architect",
      "country": "RU",
      "a": "6",
      "b": "10",
      "c": "7",
      "d": "15",
      "e": "23",
      "f": "27",
      "g": "3",
      "h": "12"
    },
    {
      "name": "Vladimir Polischuk",
      "title": "Software Architect",
      "country": "UA",
      "a": "3",
      "b": "10",
      "c": "13",
      "d": "6",
      "e": "12",
      "f": "29",
      "g": "20",
      "h": "9"
    },
    {
      "name": "Stephan Smith",
      "title": "Java Chief Architect",
      "country": "US",
      "a": "7",
      "b": "5",
      "c": "4",
      "d": "6",
      "e": "30",
      "f": "20",
      "g": "11",
      "h": "18"
    },
    {
      "name": "Vivek Kumar",
      "title": "Senior Architect",
      "country": "IN",
      "a": "9",
      "b": "1",
      "c": "4",
      "d": "9",
      "e": "27",
      "f": "17",
      "g": "15",
      "h": "18"
    },
    {
      "name": "Bhaskar Rao",
      "title": "Senior Software Engineer",
      "country": "IN",
      "a": "4",
      "b": "2",
      "c": "15",
      "d": "19",
      "e": "19",
      "f": "21",
      "g": "15",
      "h": "3"
    },
    {
      "name": "Matthew Webster",
      "title": "DevOps Architect",
      "country": "US",
      "a": "0",
      "b": "1",
      "c": "6",
      "d": "7",
      "e": "24",
      "f": "17",
      "g": "16",
      "h": "26"
    },
    {
      "name": "Arun Kannan",
      "title": "Senior Engineer",
      "country": "IN",
      "a": "1",
      "b": "4",
      "c": "2",
      "d": "1",
      "e": "16",
      "f": "21",
      "g": "19",
      "h": "33"
    },
    {
      "name": "Ivan Yuriev",
      "title": "Systems Architect",
      "country": "RU",
      "a": "9",
      "b": "8",
      "c": "6",
      "d": "11",
      "e": "15",
      "f": "25",
      "g": "12",
      "h": "9"
    },
    {
      "name": "Pavel Vinogradov",
      "title": "OpenStack Operations Engineer",
      "country": "BY",
      "a": "3",
      "b": "1",
      "c": "13",
      "d": "3",
      "e": "30",
      "f": "0",
      "g": "35",
      "h": "8"
    },
    {
      "name": "Sajan Nair",
      "title": "Cloud Platform Architect",
      "country": "IN",
      "a": "2",
      "b": "0",
      "c": "4",
      "d": "19",
      "e": "9",
      "f": "10",
      "g": "23",
      "h": "23"
    },
    {
      "name": "Alexander Makarov",
      "title": "Lead Developer",
      "country": "BY",
      "a": "7",
      "b": "1",
      "c": "11",
      "d": "19",
      "e": "10",
      "f": "27",
      "g": "1",
      "h": "13"
    },
    {
      "name": "Sho Uchida",
      "title": "Cloud Platform Architect",
      "country": "JP",
      "a": "3",
      "b": "4",
      "c": "10",
      "d": "9",
      "e": "28",
      "f": "15",
      "g": "9",
      "h": "10"
    },
    {
      "name": "Jason Hu",
      "title": "Lead Developer",
      "country": "CN",
      "a": "7",
      "b": "4",
      "c": "13",
      "d": "5",
      "e": "0",
      "f": "17",
      "g": "18",
      "h": "22"
    },
    {
      "name": "Alexander Dubinin",
      "title": "Lead Frontend Developer",
      "country": "RU",
      "a": "4",
      "b": "7",
      "c": "8",
      "d": "11",
      "e": "9",
      "f": "14",
      "g": "15",
      "h": "17"
    },
    {
      "name": "Paul Bryant",
      "title": "Senior Software Engineer",
      "country": "US",
      "a": "10",
      "b": "2",
      "c": "2",
      "d": "2",
      "e": "19",
      "f": "13",
      "g": "23",
      "h": "14"
    },
    {
      "name": "Dmitry Afanasiev",
      "title": "Senior Architect",
      "country": "RU",
      "a": "4",
      "b": "1",
      "c": "8",
      "d": "15",
      "e": "0",
      "f": "10",
      "g": "35",
      "h": "12"
    },
    {
      "name": "Amit Ranjan",
      "title": "IT Architect",
      "country": "IN",
      "a": "7",
      "b": "1",
      "c": "19",
      "d": "20",
      "e": "3",
      "f": "29",
      "g": "3",
      "h": "1"
    },
    {
      "name": "Andrey Knyazev",
      "title": "Senior Systems Engineer",
      "country": "BY",
      "a": "8",
      "b": "8",
      "c": "14",
      "d": "19",
      "e": "7",
      "f": "4",
      "g": "4",
      "h": "16"
    },
    {
      "name": "Alexander Vasilenko",
      "title": "DevOps Architect",
      "country": "RU",
      "a": "5",
      "b": "2",
      "c": "8",
      "d": "10",
      "e": "23",
      "f": "19",
      "g": "4",
      "h": "7"
    },
    {
      "name": "Gunjan Sharma",
      "title": "OpenStack Operations Engineer",
      "country": "IN",
      "a": "7",
      "b": "10",
      "c": "3",
      "d": "4",
      "e": "14",
      "f": "7",
      "g": "19",
      "h": "13"
    },
    {
      "name": "Jake liu",
      "title": "Senior Software Engineer",
      "country": "CN",
      "a": "3",
      "b": "7",
      "c": "14",
      "d": "4",
      "e": "4",
      "f": "7",
      "g": "11",
      "h": "25"
    },
    {
      "name": "Senthil Nathan",
      "title": "Architect",
      "country": "IN",
      "a": "10",
      "b": "8",
      "c": "10",
      "d": "2",
      "e": "6",
      "f": "2",
      "g": "7",
      "h": "29"
    },
    {
      "name": "Alexander Chekanov",
      "title": "Java Chief Architect",
      "country": "RU",
      "a": "7",
      "b": "8",
      "c": "6",
      "d": "9",
      "e": "19",
      "f": "10",
      "g": "0",
      "h": "14"
    },
    {
      "name": "Oleg Tsvetkov",
      "title": "Senior Systems Engineer",
      "country": "UA",
      "a": "2",
      "b": "4",
      "c": "15",
      "d": "2",
      "e": "2",
      "f": "19",
      "g": "0",
      "h": "29"
    },
    {
      "name": "Ritesh Pandey",
      "title": "Software Architect",
      "country": "IN",
      "a": "3",
      "b": "4",
      "c": "1",
      "d": "19",
      "e": "16",
      "f": "7",
      "g": "10",
      "h": "11"
    },
    {
      "name": "Rahul Kumar",
      "title": "OpenStack Operations Engineer",
      "country": "IN",
      "a": "4",
      "b": "8",
      "c": "10",
      "d": "4",
      "e": "6",
      "f": "3",
      "g": "5",
      "h": "29"
    },
    {
      "name": "Oleg Makas ",
      "title": "Cloud Platform Architect",
      "country": "BY",
      "a": "8",
      "b": "9",
      "c": "7",
      "d": "19",
      "e": "9",
      "f": "6",
      "g": "10",
      "h": "0"
    },
    {
      "name": "Ajay Raut",
      "title": "Java Chief Architect",
      "country": "IN",
      "a": "2",
      "b": "8",
      "c": "4",
      "d": "2",
      "e": "3",
      "f": "16",
      "g": "27",
      "h": "2"
    },
    {
      "name": "Sergey Kovalev",
      "title": "Senior Architect",
      "country": "RU",
      "a": "4",
      "b": "7",
      "c": "8",
      "d": "11",
      "e": "7",
      "f": "2",
      "g": "19",
      "h": "0"
    },
    {
      "name": "Dmytro Marchuk",
      "title": "Lead Developer",
      "country": "UA",
      "a": "5",
      "b": "4",
      "c": "5",
      "d": "8",
      "e": "3",
      "f": "16",
      "g": "11",
      "h": "0"
    },
    {
      "name": "Vadim Goncharenko",
      "title": "Software Architect",
      "country": "RU",
      "a": "3",
      "b": "3",
      "c": "5",
      "d": "1",
      "e": "10",
      "f": "10",
      "g": "4",
      "h": "13"
    }
  ]
};